
# --- !Ups

INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Admiral', 10.6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Ahtanum', 5.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Cascade', 6.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Centennial', 9.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Challenger', 6.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Chinook', 11.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Citra', 11.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Cluster', 5.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Columbia', 5.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Columbus', 14.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Cornet', 9.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Crystal', 4.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Amarillo', 8.6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'D Saaz', 5.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'East Kent Golding', 4.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Eroica', 2.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'First Gold', 7.9);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Fuggles', 5.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Galaxy', 13.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Galena', 12.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Galena', 5.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Green Bullet', 13.6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Hallertau Aroma', 8.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Aquila', 6.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Hallertau Mittlefrueh', 6.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Hallertau Tradition', 5.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Herald', 12);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Hersbrucker', 2.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Horizon', 13);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Liberty', 4.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Lublin', 5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Magnum', 12.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Marco Polo', 12);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Millennium', 14.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'B Saaz', 6.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Mt. Hood', 5.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Nelson Sauvin', 12.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Newport', 11);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Northdown', 8.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Northern Brewer', 9.6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Nugget', 8.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Opal', 10);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Orion', 7.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pacific Gem', 13.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pacific Hallertau', 5.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Banner', 10);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pacific Jade', 15.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Palisade', 7.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Perle', 6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Phoenix', 8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pilgrim', 10.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pioneer', 9.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Pride of Ringwood', 8.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Progress', 7.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Saaz', 3.6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Santiam', 6.7);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Boadicea', 7.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Saphire', 4.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Simcoe', 12.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Smaragd', 8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Sorachi', 11.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Southern Cross', 14.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Spalt', 4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Sterling', 7.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Stickebract', 14);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Strisselspalt', 2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Styrian Golding', 4.4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Bramling Cross', 5.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Sun', 14);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Super Alpha', 12);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Super Pride', 13);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Target', 9);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Tarus', 13);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Tettnanger', 4);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Topaz', 16.2);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Tradition', 6);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Ultra', 3.3);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Vanguard', 5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Brewers Gold', 5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Warrior', 15.8);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Willamette', 7.1);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Zeus', 13.5);
INSERT INTO hop (id,name, alpha_acid) VALUES (hop_seq.nextval, 'Bullion', 9.5);

INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('1A', 'Light Lager','Lite American Lager',8,12,2,3,1.028,1.04,0.998,1.008,2.8,4.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('1B', 'Light Lager','Standard American Lager',8,15,2,4,1.04,1.05,1.004,1.01,4.2,5.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('1C', 'Light Lager','Premium American Lager',15,25,2,6,1.046,1.056,1.008,1.012,4.6,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('1D', 'Light Lager','Munich Helles',16,22,3,5,1.045,1.051,1.008,1.012,4.7,5.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('1E', 'Light Lager','Dortmunder Export',23,30,4,6,1.048,1.056,1.01,1.015,4.8,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('2A', 'Pilsner','German Pilsner (Pils)',25,45,2,5,1.044,1.05,1.008,1.013,4.4,5.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('2B', 'Pilsner','Bohemian Pilsener',35,45,3.5,6,1.044,1.056,1.013,1.017,4.2,5.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('2C', 'Pilsner','Classic American Pilsner',25,40,3,6,1.044,1.06,1.01,1.015,4.5,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('3A', 'European Amber Lager','Vienna Lager',18,30,10,16,1.046,1.052,1.01,1.014,4.5,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('3B', 'European Amber Lager','Oktoberfest/Märzen',20,28,7,14,1.05,1.057,1.012,1.016,4.8,5.7);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('4A', 'Dark Lager','Dark American Lager',8,20,14,22,1.044,1.056,1.008,1.012,4.2,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('4B', 'Dark Lager','Munich Dunkel',18,28,14,28,1.048,1.056,1.01,1.016,4.5,5.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('4C', 'Dark Lager','Schwarzbier (Black Beer)',22,32,17,30,1.046,1.052,1.01,1.016,4.4,5.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('5A', 'Bock','Maibock/Helles Bock',23,35,6,11,1.064,1.072,1.011,1.018,6.3,7.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('5B', 'Bock','Traditional Bock',20,27,14,22,1.064,1.072,1.013,1.019,6.3,7.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('5C', 'Bock','Doppelbock',16,26,6,25,1.072,1.112,1.016,1.024,7,10);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('5D', 'Bock','Eisbock',25,35,18,30,1.078,1.12,1.02,1.035,9,14);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('6A', 'Light Hybrid Beer','Cream Ale',15,20,2.5,5,1.042,1.055,1.006,1.012,4.2,5.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('6B', 'Light Hybrid Beer','Blonde Ale',15,28,3,6,1.038,1.054,1.008,1.013,3.8,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('6C', 'Light Hybrid Beer','Kölsch',20,30,3.5,5,1.044,1.05,1.007,1.011,4.4,5.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('6D', 'Light Hybrid Beer','American Wheat or Rye Beer',15,30,3,6,1.04,1.055,1.008,1.013,4,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('7A', 'Amber Hybrid Beer','Northern German Altbier',25,40,13,19,1.046,1.054,1.01,1.015,4.5,5.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('7B', 'Amber Hybrid Beer','California Common Beer',30,45,10,14,1.048,1.054,1.011,1.014,4.5,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('7C', 'Amber Hybrid Beer','Düsseldorf Altbier',35,50,11,17,1.046,1.054,1.01,1.015,4.5,5.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('8A', 'English Pale Ale','Standard/Ordinary Bitter',25,35,4,14,1.032,1.04,1.007,1.011,3.2,3.8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('8B', 'English Pale Ale','Special/Best/Premium Bitter',25,40,5,16,1.04,1.048,1.008,1.012,3.8,4.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('8C', 'English Pale Ale','Extra Special/Strong Bitter (English Pale Ale)',30,50,6,18,1.048,1.06,1.01,1.016,4.6,6.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('9A', 'Scottish And Irish Ale','Scottish Light 60/-',10,20,9,17,1.03,1.035,1.01,1.013,2.5,3.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('9B', 'Scottish And Irish Ale','Scottish Heavy 70/-',10,25,9,17,1.035,1.04,1.01,1.015,3.2,3.9);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('9C', 'Scottish And Irish Ale','Scottish Export 80/-',15,30,9,17,1.04,1.054,1.01,1.016,3.9,5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('9D', 'Scottish And Irish Ale','Irish Red Ale',17,28,9,18,1.044,1.06,1.01,1.014,4,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('9E', 'Scottish And Irish Ale','Strong Scotch Ale',17,35,14,25,1.07,1.13,1.018,1.056,6.5,10);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('10A', 'American Ale','American Pale Ale',30,45,5,14,1.045,1.06,1.01,1.015,4.5,6.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('10B', 'American Ale','American Amber Ale',25,40,10,17,1.045,1.06,1.01,1.015,4.5,6.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('10C', 'American Ale','American Brown Ale',20,40,18,35,1.045,1.06,1.01,1.016,4.3,6.2);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('11A', 'English Brown Ale','Mild',10,25,12,25,1.03,1.038,1.008,1.013,2.8,4.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('11B', 'English Brown Ale','Southern English Brown',12,20,19,35,1.033,1.042,1.011,1.014,2.8,4.1);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('11C', 'English Brown Ale','Northern English Brown Ale',20,30,12,22,1.04,1.052,1.008,1.013,4.2,5.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('12A', 'Porter','Brown Porter',18,35,20,30,1.04,1.052,1.008,1.014,4,5.4);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('12B', 'Porter','Robust Porter',25,50,22,35,1.048,1.065,1.012,1.016,4.8,6.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('12C', 'Porter','Baltic Porter',20,40,17,30,1.06,1.09,1.016,1.024,5.5,9.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13A', 'Stout','Dry Stout',30,45,25,40,1.036,1.05,1.007,1.011,4,5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13B', 'Stout','Sweet Stout',20,40,30,40,1.044,1.06,1.012,1.024,4,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13C', 'Stout','Oatmeal Stout',25,40,22,40,1.048,1.065,1.01,1.018,4.2,5.9);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13D', 'Stout','Foreign Extra Stout',30,70,30,40,1.056,1.075,1.01,1.018,5.5,8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13E', 'Stout','American Stout',35,75,30,40,1.05,1.075,1.01,1.022,5,7);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('13F', 'Stout','Russian Imperial Stout',50,90,30,40,1.075,1.115,1.018,1.03,8,12);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('14A', 'India Pale Ale (ipa)','English IPA',40,60,8,14,1.05,1.075,1.01,1.018,5,7.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('14B', 'India Pale Ale (ipa)','American IPA',40,70,6,15,1.056,1.075,1.01,1.018,5.5,7.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('14C', 'India Pale Ale (ipa)','Imperial IPA',60,120,8,15,1.07,1.09,1.01,1.02,7.5,10);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('15A', 'German Wheat And Rye Beer','Weizen/Weissbier',8,15,2,8,1.044,1.052,1.01,1.014,4.3,5.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('15B', 'German Wheat And Rye Beer','Dunkelweizen',10,18,14,23,1.044,1.056,1.01,1.014,4.3,5.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('15C', 'German Wheat And Rye Beer','Weizenbock',15,30,12,25,1.064,1.09,1.015,1.022,6.5,8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('15D', 'German Wheat And Rye Beer','Roggenbier (German Rye Beer)',10,20,14,19,1.046,1.056,1.01,1.014,4.5,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('16A', 'Belgian And French Ale','Witbier',10,20,2,4,1.044,1.052,1.008,1.012,4.5,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('16B', 'Belgian And French Ale','Belgian Pale Ale',20,30,8,14,1.048,1.054,1.01,1.014,4.8,5.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('16C', 'Belgian And French Ale','Saison',20,35,5,14,1.048,1.065,1.002,1.012,5,7);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('16D', 'Belgian And French Ale','Bière de Garde',18,28,6,19,1.06,1.08,1.008,1.016,6,8.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('16E', 'Belgian And French Ale','Belgian Specialty Ale',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17A', 'Sour Ale','Berliner Weisse',3,8,2,3,1.028,1.032,1.003,1.006,2.8,3.8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17B', 'Sour Ale','Flanders Red Ale',10,25,10,16,1.048,1.057,1.002,1.012,4.6,6.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17C', 'Sour Ale','Flanders Brown Ale/Oud Bruin',20,25,15,22,1.04,1.074,1.008,1.012,4,8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17D', 'Sour Ale','Straight (Unblended) Lambic',0,10,3,7,1.04,1.054,1.001,1.01,5,6.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17E', 'Sour Ale','Gueuze',0,10,3,7,1.04,1.06,1,1.006,5,8);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('17F', 'Sour Ale','Fruit Lambic',0,10,3,7,1.04,1.06,1,1.01,5,7);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('18A', 'Belgian Strong Ale','Belgian Blond Ale',15,30,4,7,1.062,1.075,1.008,1.018,6,7.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('18B', 'Belgian Strong Ale','Belgian Dubbel',15,25,10,17,1.062,1.075,1.008,1.018,6,7.6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('18C', 'Belgian Strong Ale','Belgian Tripel',20,40,4.5,7,1.075,1.085,1.008,1.014,7.5,9.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('18D', 'Belgian Strong Ale','Belgian Golden Strong Ale',22,35,3,6,1.07,1.095,1.005,1.016,7.5,10.5);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('18E', 'Belgian Strong Ale','Belgian Dark Strong Ale',20,35,12,22,1.075,1.11,1.01,1.024,8,11);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('19A', 'Strong Ale','Old Ale',30,60,10,22,1.06,1.09,1.015,1.022,6,9);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('19B', 'Strong Ale','English Barleywine',35,70,8,22,1.08,1.12,1.018,1.03,8,12);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('19C', 'Strong Ale','American Barleywine',50,120,10,19,1.08,1.12,1.016,1.03,8,12);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('20', 'Fruit Beer','Fruit Beer',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('21A', 'Spice/herb/vegetable Beer','Spice, Herb, or Vegetable Beer',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('21B', 'Spice/herb/vegetable Beer','Christmas/Winter Specialty Spiced Beer',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('22A', 'Smoke-flavored/wood-aged Beer','Classic Rauchbier',20,30,12,22,1.05,1.07,1.012,1.016,4.8,6);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('22B', 'Smoke-flavored/wood-aged Beer','Other Smoked Beer',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('22C', 'Smoke-flavored/wood-aged Beer','Wood-Aged Beer',null,null,null,null,null,null,null,null,null,null);
INSERT INTO style (code,category,sub_category,ibu_min,ibu_max,srm_min,srm_max,og_min,og_max,fg_min,fg_max,abv_min,abv_max) VALUES ('23', 'Specialty Beer','Specialty Beer',null,null,null,null,null,null,null,null,null,null);

# --- !Downs

Delete from hop;